test behat dumps

diff --git a/.github/workflows/moodle-plugin-ci.yml b/.github/workflows/moodle-plugin-ci.yml
--- a/.github/workflows/moodle-plugin-ci.yml
+++ b/.github/workflows/moodle-plugin-ci.yml
@@ -4,7 +4,7 @@ on: [push, pull_request]
 
 jobs:
   test:
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
 
     services:
       postgres:
@@ -34,45 +34,45 @@ jobs:
           - php: 7.4
             moodle-branch: MOODLE_401_STABLE
             database: mariadb
-          - php: 7.4
-            moodle-branch: MOODLE_401_STABLE
-            database: pgsql
-          - php: 8.0
-            moodle-branch: MOODLE_401_STABLE
-            database: mariadb
-          - php: 8.0
-            moodle-branch: MOODLE_401_STABLE
-            database: pgsql
-          - php: 8.1
-            moodle-branch: MOODLE_401_STABLE
-            database: mariadb
-          - php: 8.1
-            moodle-branch: MOODLE_401_STABLE
-            database: pgsql
-          - php: 8.1
-            moodle-branch: MOODLE_402_STABLE
-            database: mariadb
-          - php: 8.1
-            moodle-branch: MOODLE_402_STABLE
-            database: pgsql
-          - php: 8.1
-            moodle-branch: MOODLE_403_STABLE
-            database: mariadb
-          - php: 8.1
-            moodle-branch: MOODLE_403_STABLE
-            database: pgsql
-          - php: 8.2
-            moodle-branch: MOODLE_402_STABLE
-            database: mariadb
-          - php: 8.2
-            moodle-branch: MOODLE_402_STABLE
-            database: pgsql
-          - php: 8.2
-            moodle-branch: MOODLE_403_STABLE
-            database: mariadb
-          - php: 8.2
-            moodle-branch: MOODLE_403_STABLE
-            database: pgsql
+#          - php: 7.4
+#            moodle-branch: MOODLE_401_STABLE
+#            database: pgsql
+#          - php: 8.0
+#            moodle-branch: MOODLE_401_STABLE
+#            database: mariadb
+#          - php: 8.0
+#            moodle-branch: MOODLE_401_STABLE
+#            database: pgsql
+#          - php: 8.1
+#            moodle-branch: MOODLE_401_STABLE
+#            database: mariadb
+#          - php: 8.1
+#            moodle-branch: MOODLE_401_STABLE
+#            database: pgsql
+#          - php: 8.1
+#            moodle-branch: MOODLE_402_STABLE
+#            database: mariadb
+#          - php: 8.1
+#            moodle-branch: MOODLE_402_STABLE
+#            database: pgsql
+#          - php: 8.1
+#            moodle-branch: MOODLE_403_STABLE
+#            database: mariadb
+#          - php: 8.1
+#            moodle-branch: MOODLE_403_STABLE
+#            database: pgsql
+#          - php: 8.2
+#            moodle-branch: MOODLE_402_STABLE
+#            database: mariadb
+#          - php: 8.2
+#            moodle-branch: MOODLE_402_STABLE
+#            database: pgsql
+#          - php: 8.2
+#            moodle-branch: MOODLE_403_STABLE
+#            database: mariadb
+#          - php: 8.2
+#            moodle-branch: MOODLE_403_STABLE
+#            database: pgsql
 
     steps:
       - name: Check out repository code
@@ -98,7 +98,10 @@ jobs:
 
       - name: Install moodle-plugin-ci
         run: |
+          mkdir -p /home/runner/work/behat_dump
           moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
+          moodle-plugin-ci add-config '$CFG->behat_increasetimeout = 2;'
+          moodle-plugin-ci add-config '$CFG->behat_faildump_path = "/home/runner/work/behat_dump";'
         env:
           DB: ${{ matrix.database }}
           MOODLE_BRANCH: ${{ matrix.moodle-branch }}
@@ -107,49 +110,65 @@ jobs:
           PHPDOCCHECKER_IGNORE_PATHS: /^classes\/vendor/
           MUSTACHE_IGNORE_NAMES: 'report.mustache,questionnaire.mustache'
 
-      - name: PHP Lint
-        if: ${{ always() }}
-        run: moodle-plugin-ci phplint
+#      - name: PHP Lint
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci phplint
+#
+#      - name: PHP Copy/Paste Detector
+#        continue-on-error: true # This step will show errors but will not fail
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci phpcpd
+#
+#      - name: PHP Mess Detector
+#        continue-on-error: true # This step will show errors but will not fail
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci phpmd
+#
+#      - name: Moodle Code Checker
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci phpcs --max-warnings 0 || true
+#
+#      - name: Moodle PHPDoc Checker
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci phpdoc || true
+#
+#      - name: Validating
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci validate
+#
+#      - name: Check upgrade savepoints
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci savepoints
+#
+#      - name: Mustache Lint
+#        continue-on-error: true # This step will show errors but will not fail
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci mustache
+#
+#      - name: Grunt
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci grunt || true
+#
+#      - name: PHPUnit tests
+#        if: ${{ always() }}
+#        run: moodle-plugin-ci phpunit --coverage-text || true
 
-      - name: PHP Copy/Paste Detector
-        continue-on-error: true # This step will show errors but will not fail
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpcpd
-
-      - name: PHP Mess Detector
-        continue-on-error: true # This step will show errors but will not fail
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpmd
-
-      - name: Moodle Code Checker
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpcs --max-warnings 0 || true
-
-      - name: Moodle PHPDoc Checker
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpdoc || true
-
-      - name: Validating
-        if: ${{ always() }}
-        run: moodle-plugin-ci validate
-
-      - name: Check upgrade savepoints
-        if: ${{ always() }}
-        run: moodle-plugin-ci savepoints
-
-      - name: Mustache Lint
-        continue-on-error: true # This step will show errors but will not fail
-        if: ${{ always() }}
-        run: moodle-plugin-ci mustache
-
-      - name: Grunt
-        if: ${{ always() }}
-        run: moodle-plugin-ci grunt || true
-
-      - name: PHPUnit tests
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpunit --coverage-text || true
+      - name: Setup upterm session
+        uses: lhotari/action-upterm@v1
 
       - name: Behat features
         if: ${{ always() }}
-        run: moodle-plugin-ci behat --profile chrome
+        working-directory: moodle
+        run: |
+            php admin/tool/behat/cli/init.php
+            moodle-plugin-ci behat --profile=chrome
+        env:
+          dbtype: ${{ matrix.database }}
+          MOODLE_START_BEHAT_SERVERS: YES
+
+      - name: Upload behat dump.
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v2.3.1
+        with:
+          name: behat-dump
+          path: /home/runner/work/behat_dump
